### ISSUE TITLE
Biosample page content rendering

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#30]
Some concerns with how the biosample page is constructed:

- [x]  Side links opens new content boxes above Summary box, which to me is very non intuitive, shouldn't they open below or replace the summary box?

- [x]  Tabs open a box even if it is empty (no properties) - optimal solution would be for us to add some properties for all biosamples and to also make sure display makes sense even if there aren't any properties. This could mean hiding the sidebar link (best) or creating a sentence in the box such as "no properties available." (less good but ok)

- [ ]  Contact box is weird (under summary). First, its constructed even if there is no contact (again, best solution, all biosamples need a contact. but secondarily, we should gracefully handle the no contact situation). Also, even when there is a contact, the type and description are empty, I'm not sure what those are.

**Comment by almasaeed2010** [comment]
1. fixed using theme override
2. Properties field is part of tripal core. If it returned an null instead of the empty array, it will auto disappear.
3. Contact field is part of tripal core and should also return null instead of an empty table.

**Comment by bradfordcondon** [comment]
* Core has been updated so If no contacts, field properly nulls.  (the problem was biomaterial base table uses a weird column name instead of contact_id, so its hard-coded in as an exception.  But then it wasnt nulling if no contact for the exception...)

>Also, even when there is a contact, the type and description are empty, I'm not sure what those are.

* The contact base table has a type_id column and a description column.  We could a) write our own formatter b) make a PR so that if no contacts have a descriptio nor type, dont display those columns c) edit our db to add type and description.

I am a fan of b) because we don't have that many contacts, it's part of the base table, and if we add contacts with descriptions or type_id's later, then we'll be SOL.  I've made a new issue for this solution  #81   but we can also discuss further there.
