### ISSUE TITLE
Database Statistics

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#319]
We need to report statistics for the content of our database:

>Hi Jill and Meg,
>
>Is it possible for you to provide numbers for the data types in your databases such as we are reporting for GDR and CGD?
>
>e.g. At the end of year 2  GDR contains 21 genomes; 528,890 genes; 1,967 species; 14,382 >germplasm; 287 genetic maps; 3,249,946 markers; 3,671 QTLs and 101 MTLs for 353 agronomic traits; >402,159 phenotypic measurements, 10,806,585 genotypic measurements and 7,404 publications.
>
>Thanks
>Dorrie

**Comment by bradfordcondon** [comment]
We get all this for free if we can figure out how to re-enable the dashboard (minus things we dont have bundles for).

I'll work on getting it back.

**Comment by bradfordcondon** [comment]
dashboard added at 
https://www.hardwoodgenomics.org/admin/dashboard

**Comment by bradfordcondon** [comment]
| content                 | table         | count    |
|-------------------------|---------------|----------|
| expression data         | elementresult | 27330271 |
| mRNA contig             | feature       | 982549   |
| mRNA                    | feature       | 315134   |
| Gene                    | feature       | 22674    |
| Biological Sample       | biomaterial   | 324      |
| BLAST Annotations       | analysis      | 50       |
| Organism                | organism      | 34       |
| Transcriptome Assembly  | analysis      | 26       |
| Interproscan annotation | analysis      | 26       |
| Genome                  | analysis      | 11       |
| BAC library             | library       | 10       |
| Expression profile      | analysis      | 8        |
| Publication             | pub           | 5        |
| Map                     | map           | 2        |
| Genomic library         | library       | 1        |


Written up:
(note 33 instead of 34 because of chinese chestnut QTL

HWG houses genomic data for 33 organisms, with a total of 26 transcriptome assemblies and 11 Genome assemblies (including archived content).  There are 22674  + 315134 = genes from assembled genomes and an additional 982549 mRNA contigs from draft transcriptome assemblies.  Differential expression data is avialable for 8 organisms derived from 324 unique biosamples,  with 27330271 gene x biosamples expression values.
