### ISSUE TITLE
add/describe fields for analysis types - genome, transcriptome, blast, ips 

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#375]
### Feature description
It makes sense to have a standard set of fields for genome and transcriptome analyses that are more detailed than what we have now, to guide curation and create a consistent user experience. Here are suggestions to get the ball rolling.

- New fields for transcriptome analysis
  - file download - free text, encourage curator to link to all relevant flat files
  - NCBI link out (if available)
    - Done for most: #393
- Descriptions/instructions for current fields that are a mess
  - source name - Write a short description of the data such as "RNASeq from beech leaves, ozone treatment experiment" or "RNASeq from a variety of tissues" 
  - source version - lets just use the date again

- New fields for genome analysis
  - file download - free text, encourage curator to link to all relevant flat files
  - jbrowse link
  - number of scaffolds
  - total length of assembly
  - NCBI link out (if available)
       - (Done: see #392 )
  - number of annotated genes
- Descriptions/instructions for current fields that are a mess
  - source name - Write a short description of the data such as "DNA from cultivar 'Vanuxem'" 
  - source version - each community probably has an internal versioning system that we should try to adopt

**Comment by bradfordcondon** [comment]
## Responses questions affirmations

>NCBI link out (if available)

this is an existing field: DBXref.

>file download - free text, encourage curator to link to all relevant flat files

I can see this working, in that you would have a download field with infinite cardinality.  On creating/editing the entry, you set the value to the path on the server.  The formatter then would build it into a nice table.  The widget would either need to be the full formatted link `<a href="www.something.com"> Full Transcriptome Download</a>` OR two text boxes, one for the file location and one for the text.
i still have trouble believing that there isnt an existing "raw file" field for Drupal that couldnt handle this for us: theres nothing inherently  Tripal about it.

Why no assembly statistics?  I would think total number of reads, number of assembled genes mRNA contigs, should be generally reported in the pub?

#### source name and version, program name and version
Here are the Chado descriptions from the wiki (and in the column description i believe):

* Source name, e.g. cDNA, SwissProt.
* Program name, e.g. blastx, blastp, sim4, genscan.
* Version description, e.g. TBLASTX 2.0MP-WashU [09-Nov-2000].
* Algorithm name, e.g. blast.
* source version: No instructions given


>source version - lets just use the date again

I think this is a good solution.  However if we're going to use the community version for Genome Analysis, why not also for the transcriptome?  And if there is no obvious version i think n/a or 1.0 is ok?

>source name - Write a short description of the data such as "RNASeq from beech leaves, ozone treatment experiment" or "RNASeq from a variety of tissues"

The analytical source of a transcriptome assembly would be the RNAseq reads, right?  Is it enough to say RNAseq?  If not we can go with your suggestion but might be hard to keep uniform across transcriptomes.

## Further thoughts

The most helpful thing will be to alter the WIDGET DESCRIPTION, ie, what someone sees as the instructions when they are editing/creating the analysis.  Adding it to the wiki is great but there are a few sources of truth in the wiki now and when batch creating one can overlook/misremember.

Fortunately, the help text for **each field instance** can be configured on the site (see below screenshot: we would alter the value in the help text box).  So that means we can write the help text specific for HWG to ensure uniform data entry for the field.

<img width="1346" alt="screen shot 2018-08-15 at 9 00 06 am" src="https://user-images.githubusercontent.com/7063154/44149325-b5184788-a069-11e8-9bee-30210520fccc.png">

**Comment by bradfordcondon** [comment]
This is core's file module.  

![image](https://user-images.githubusercontent.com/7063154/44149703-fec25ee0-a06a-11e8-96a0-6c4a31767753.png)

If we can have infinite cardinality, and provide some theming for the display, wouldn't this work for us?  

https://www.drupal.org/docs/7/core/modules/file/overview

The main problem is that the info isn't stored in Chado and therefore vulnerable to loss of support in migrations.

**Comment by mestato** [comment]
>Why no assembly statistics for transcriptome? I would think total number of reads, number of assembled genes mRNA contigs, should be generally reported in the pub?

We already have number of contigs and average contig length, which I just change to number of transcripts and average transcript length. Number of reads can be hard to find.

>source version - lets just use the date again
>I think this is a good solution. However if we're going to use the community version for Genome Analysis, why not also for the transcriptome? And if there is no obvious version i think n/a or 1.0 is ok?

No one uses versions on transcriptomes like they do genomes, since they rarely build on each other. There may be more than one per species, but they are usually totally independent efforts, not refinements of previous efforts. Which is why I thought actually v1, v2, v3 would be confusing. I think my absolute optimal would be Last Name - Date (i.e. "Carlson-080818" or "Staton-020304"), since I tend to associate the details of a dataset with the lab it came from. But the last name gets sticky, since do you use first author or lab PI or is it a group effort? Thus I decided date might be safest and easiest.

> The analytical source of a transcriptome assembly would be the RNAseq reads, right? Is it enough to say RNAseq? If not we can go with your suggestion but might be hard to keep uniform across transcriptomes.

Yes, 'RNASeq' would be easiest and I suppose it would be fine if we can't find any info on the samples. But I like having some information on the source of the RNA, because that information isn't available elsewhere - we aren't associating biosamples with transcriptome analyses. Even if there's a gene expression experiment and we have a set of biosamples, they are attached to an organism not the analysis, at least from the user perspective. (And yes, it would be a lot of extra work to import biosamples for every genome and transcriptome, and NCBI takes care of that, so lets not do it.) So I was thinking it would be nice to have a bit more info about what types of samples. But a default of "RNASeq" would be fine. 

I updated the data source field widget to say "The source where data was obtained for this analysis. Write a short description of the data such as "RNASeq from beech leaves, ozone treatment experiment" or "RNASeq from a variety of tissues". If no information on the RNASeq libraries can be found a default of "RNASeq" is ok."

**Comment by bradfordcondon** [comment]
Took care of the dbxrefs (NCBI biotaxon links). I got most of them, a few were ambiguous and i didnt fill them in (see #393).
We need to add something ab out dbxrefs to the instructions (particularly that you need ot insert the accession as a cvterm to link it).

**Comment by bradfordcondon** [comment]
Property fields:
here's what we've currently got.  They would be created automatically from existing chado props.
We can define new props.  We can even set them to be **required** if we want.


### Genome

None.


### Transcriptome
* Number of transcripts (local term)
* Average transcript length (local term)

**Comment by bradfordcondon** [comment]
# Transcriptome assembly field labeling:

### Data source
 
The source where data was obtained for this analysis. Write a short description of the data such as "RNASeq from beech leaves, ozone treatment experiment" or "RNASeq from a variety of tissues". If no information on the RNASeq libraries can be found a default of "RNASeq" is ok.

### Data version (actually program version?  this looks like a point of confusion actually).

HWG uses the date performed IE 09-11-2000 for the program version

# Genome fields:

### Data source

The source where data was obtained for this analysis.  Write a short description of the data such as "DNA from cultivar 'Vanuxem'"

### Data version (program version?)

Full genome assemblies have a version name associated with them. Please try to use whatever version name the community has christened this assembly with.


### Property fields

Local terms created for all.

* number of annotated genes
* number of scaffolds
* total assembly size

**Comment by bradfordcondon** [comment]
OK, we're all set. 

Note- I did **not** make the property fields, but i could if we want.

Here's the links:

* https://www.hardwoodgenomics.org/bio_data/add/20
* https://www.hardwoodgenomics.org/bio_data/add/21


@mestato Please look at the links and 👍 👎  we can discuss more or close this out.

**Comment by bradfordcondon** [comment]
Additionally- update help text for cross-ref

remove annotations maybe?

**Comment by bradfordcondon** [comment]
```
The source where data was obtained for this analysis. <ul><li><b>Source name:</b>  Write a short description of the data such as "DNA from cultivar 'Vanuxem'"</li>
<li><b> Source Version:</b> Full genome assemblies have a version name associated with them. Please try to use whatever version name the community has christened this assembly with.
 </li>
</ul>
```

i dont see the typo....

**Comment by bradfordcondon** [comment]
cross ref updated to:

```
The IDs where this record may be available in other external online databases.
<br>  
Example: NCBI Biorpoject ID.
```

**Comment by bradfordcondon** [comment]
>Also, dont display some of the analysis base fields we dont make good use of

So, algorithm?  I dont think anything else is an option.
