### ISSUE TITLE
theming for galaxy workflows to make them pretty

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#376]
### Feature description
Things to make galaxy workflows pretty: spacing, and possibly hacking out silly things like "Advanced Options Hide Advanced Options" and empty drop downs.

**Comment by almasaeed2010** [comment]
Worked on this for a bit but unfortunately we can't remove the `Advanced Options` because the documents are very unstructured in terms of `HTML`. We'd have to come up with a JS solution for each workflow differently :( 

The main problem with styling these pages is that they do not use the standard drupal way of creating elements. There are so many custom classes that we don't have styling for and therefore we'd need to look at every page structure and try to predict what each class needs to do. If there is a css file somewhere for the classes it might be helpful.

**Comment by mestato** [comment]
I'll close for now and if we find them too difficult to understand for the undergrads or other users we can escalate to the module repo issue queue.
