### ISSUE TITLE
Diamond issue

### ISSUE THREAD

**Issue by cricha59** [statonlab/hardwoods_site#448]
### Bug description
Diamond Match names are not showing up when loaded into the site.
### Location
Live site
### Screenshots
![2018-11-15 3](https://user-images.githubusercontent.com/43444146/48558509-6e2e7e00-e8b7-11e8-8bd2-4c29c1e0207c.png)

**Comment by almasaeed2010** [comment]
Turns out diamond adds the hit name in Hit_id instead of Hit_def. My suggestion would be to write a simple python script that will copy hit_id to hit_def and call this fixed.

**Comment by MattHuff** [comment]
This may be an issue with the July 2018 version of the TrEMBL database; in looking at the results of a swissprot run with DIAMOND, the hit name will be in hit_def - aka where it should be - but this is not the case with the TrEMBL run. We have an earlier version still available; I'm going to run a DIAMOND job on it, and I will see if this issue carries over.

**Comment by MattHuff** [comment]
The issue arises with the way the `uniprot_trembl_plants` file is labeled. The swissprot and complete TrEMBL libraries have a header like this:

```>tr|A0A059P224|A0A059P224_9GENT NADH dehydrogenase subunit 5 OS=Asclepias coulteri OX=659948 GN=ndhF PE=3 SV=1```

However, the plant-only trembl files - for both the old and new libraries, look like this:

```>A0A059P224_9GENT```

DIAMOND is able to parse through the former with no issue, but because the latter is truncated, it is not putting it in the correct place.

@bradfordcondon Since you were the one to upload these files on the staton server, do you know how the TrEMBL plant fasta files were made? We will need a new version of the July 2018 fasta file that contains all of the information seen in the first header example.

**Comment by almasaeed2010** [comment]
So as an update to this, @MattHuff and I discovered that running diamond requires using the full database. We can't simply use the truncated `plants` one.

**Comment by MattHuff** [comment]
Use `/lustre/haven/gamma/staton/library/uniprot/diamond_db/uniprot_trembl_all.dmnd` from now on, as it has complete information that DIAMOND uses to fill `hit_def`.

**Comment by almasaeed2010** [comment]
Using the full DB helped but didn't give us the results we needed. Match names are there but aren't correct. 

I feel like we should revert to regular blast. This time around though we should split to 400 files and submit 2 separate jobs to the ACF queue (1-200, 201-400) and giving each 12 hours (totaling 24 hours).

/remind me to address this issue on November 26 at 8 am

**Comment by almasaeed2010** [comment]
Discussed and the verdict is to go back to regular blast for the time being.
