### ISSUE TITLE
Triggers for Mviews?

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#457]
### Feature description
Could implementing triggers to auto update mviews be a good thing?

**Comment by almasaeed2010** [comment]
Looked into it. It has to be done on the tripal side of things if we want to automate the process. It's  difficult to implement since we'll need to write a query reader that would analyze the query to determine what operations to listen to. I don't think it's worth going through all of that honestly.

I'll close but please feel free to reopen if you disagree.
