### ISSUE TITLE
Automated Annotation - Gene Fasta Files

### ISSUE THREAD

**Issue by MattHuff** [statonlab/hardwoods_site#470]
The current Automated Annotation protocol produces three fasta files:

* Genes
* mRNAs
* Polypeptides

The mRNA and Polypeptide fasta files contain their respective coding sequences, but the gene fasta only contains the gene name as a fasta header with no other information:

```
>QlobV1.0_C360159_0000010

>QlobV1.0_C360163_0000010

>QlobV1.0_C360243_0000010

>QlobV1.0_C360261_0000010

>QlobV1.0_C360261_0000020
```

Is this what should be expected from the annotation, or is this file lacking sequence information it needs?

**Comment by bradfordcondon** [comment]
gene sequences are derived from featureloc only (whereas the mRNA and polypeptides have the sequences stored in the feature.residues column).

If the parent fasta file (contig, scaffold) didnt have sequences, theres no way to know the gene sequence.

For the current HWG workflow, gene sequences are generally ignored.  So the answer to your question is no its fine.  But perhaps the annotation protocol shouldnt create those blank files?

(in the future, i think we'll have to start loading in the FASTA sequence of the parent scaffolds, OR we will need ot make some fixes to tripal core because it does indeed mess up fields when on hte gene entity page).

**Comment by almasaeed2010** [comment]
this is no longer an issue. We simply don't print empty sequences anymore
