### ISSUE TITLE
Multiple genome versions - GO and KEGG

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#519]
### Bug description
We have two different genome analyses and associated features w/ functional annotation loaded for C. mollissima (1.1 and 3.2). This should result in a drop down on the X-ray pane (GO and KEGG specifically) to select the genome analysis, but that isn't present. Instead results seem to be only from v1.1 features.

GO:
https://www.hardwoodgenomics.org/organism/Castanea/mollissima?tripal_pane=group_ontology

KEGG:
https://www.hardwoodgenomics.org/organism/Castanea/mollissima?tripal_pane=group_kegg_browser

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Before we dig too deep into this, I am gonna re-run the indexer to see if that helps. If it doesn't, it probably means that the functionality does not exist.

**Comment by almasaeed2010** [comment]
We might be able to get this done without having to change the indexing process by limiting results to a given analysis. We'd need to figure out how to extract unique analyses for an organism that we care about (ie interpro, go, kegg analyses only instead of all analyses).

We currently have the following info:
- Feature-Analysis association in `chado.analysisfeature`
- Entity ID in `tripal_cvterm_entity_linker`
- Analysis type in `chado.analysisfeature`

This solution however might slow down the initial loading of the tree significantly. If that's the case, we'll have to enable caching or indexing depending on how slow it gets.

**Comment by almasaeed2010** [comment]
This is now available live for the browser. Unfortunately the listing page doesn't use the same functions to build the results table so we'll have to re-implement the solution for there as well.

**Comment by almasaeed2010** [comment]
Ok I think this is ready and live.

@mestato can you take a look when you get a chance?
https://www.hardwoodgenomics.org/organism/Castanea/mollissima?tripal_pane=group_kegg_browser

**Note** this organism (as of today) does not have GO terms loaded for the new 3.2/4.1 version but does have KEGG

**Comment by almasaeed2010** [comment]
@mestato the issue we encountered in the entities list page has been fixed. It now takes into account the selected analysis.

<img width="1284" alt="Screen Shot 2019-05-10 at 7 43 59 AM" src="https://user-images.githubusercontent.com/1512664/57525563-136f5f80-72f9-11e9-947b-4411a06d936e.png">
