### ISSUE TITLE
Excelsior genome downloads missing

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#580]
There are no download files available for this genome:
https://hardwoodgenomics.org/Genome-assembly/1963052?tripal_pane=group_summary_tripalpane

- Scaffolds, CDS, peptides, and gff3 files are needed
- see https://www.ebi.ac.uk/ena/data/view/PRJEB4958
- see http://www.ashgenome.org/data
- add both of those as cross refernences
- add a description of the version

**Comment by mestato** [comment]
apparently were in a pane that disappeared #373

**Comment by almasaeed2010** [comment]
Looks like someone disabled the pane and moved the description back to the summary table. I am thinking this might have happened because someone accidentally clicked the "Apply Default Tripal Layout (will reset current layout)." What worries me though is that I can't find the field that contained the links to the downloadable files and the description field was empty! The good news is that most organisms have the data except for Excelsior. I configured the fields back to the layout we want and I am hoping no data was lost but we'll have to go through genome pages and verify that they look correct

**Comment by mestato** [comment]
When we link to TreeGenes FTP, remember to link to all files

**Comment by CaseyRichards92** [comment]
@mestato  CDS, PEP, GFF and scaffolds have been linked to Tree genes website and downloads are working correctly. Words are clickable and will download as well green button https://hardwoodgenomics.org/Genome-assembly/1963052?tripal_pane=group_downloads

**Comment by mestato** [comment]
Nice!
