### ISSUE TITLE
live site: blast error

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#79]
I ran a blast to demo the website, after job finished got an error:

<img width="1296" alt="screen shot 2018-01-13 at 1 01 04 pm" src="https://user-images.githubusercontent.com/7063154/34908706-dc9168c2-f861-11e7-91c3-e541031e57e5.png">

https://hardwoodgenomics.org/blast/report/sAKmsAbzE

**Comment by almasaeed2010** [comment]
So the error here is occurring even though everything exists and run by root. It's nothing our site ever experienced before and I am running out of ideas. Any suggestions?

**Comment by bradfordcondon** [comment]
submitted another job 1 week later against different target genome: bug persists.

**Comment by almasaeed2010** [comment]
Bug resolved.

The problem was caused by CentOS systemctl. It attempts to protect services from overriding each other's temporary files by creating a sub "private" folder in `/tmp` but PHP is not aware of the change and therefore can't access the file it thought exists.

To fix:
1- Navigate to `/etc/systemd/system/multi-user.target.wants`.
2- Edit `httpd.service`.
3- Mark `PrivateTmp` as false instead of `true`.
