### ISSUE TITLE
Should JBrowse tab change to "Alignments"?

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#84]

**Comment by bradfordcondon** [comment]
no.  In some cases the jbrowse links to the genome, not to an alignment.

In other cases, its the draft sequence aligned to another genome, true.  I'm not a huge fan of having to make new fields that are identical just so that the label of the Tripal Pane can change- I'm going to make an issue in core about this, maybe theres already a way to implement..

Jbrowse is well known enough that i think its OK to have the tab named that.  If not, "Browse sequences" is the best i can think of that covers both cases, and i dont like that too much.

**Comment by almasaeed2010** [comment]
The last I heard from core about this is the API is under construction. But once the API is available we can redo what had in Tripal 2 where the admin can choose for each organism what the tab should say and specify which part of jbrowse it should link to.

**Comment by bradfordcondon** [comment]
ok, so it is a feature that will exist in the future?  In that case let's not try to fix now because the only solution is to make two differnet jbrowse bundles.

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/issues/262

**Comment by bradfordcondon** [comment]
note the discussion:  Dynamic is not  going to happen.  You need to use two cvterms.
